name: 'JS - Snyk SCA'

on:
  push:
    branches:
      - main
  schedule:
    # This cron runs at 00:00 on every Monday
    - cron: '0 0 * * MON'
  workflow_dispatch: # Run manually.

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          ignore_dirs: 'javascript/tests'

  use-matrix:
    name: '${{ matrix.job.relativePath }}'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.job.cd }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Snyk Test
        run: |
          # Run the Snyk command and capture its exit code
          snyk test || exit_code=$?

          # Check the exit code; if it's 1 (vulnerabilities found), handle gracefully
          if [[ $exit_code -eq 1 ]]; then
            echo "Vulnerabilities found, but not failing the job."
            exit 0
          elif [[ -n $exit_code ]]; then
            # Some other error occurred
            exit $exit_code
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
