name: 'JS - Snyk'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v4.1.0

      - name: env
        run: env
        shell: bash

      - name: Matrix
        id: generate
        uses: zchryr/manifest@main
        with:
          manifest: 'package.json'
          # ignore_dirs: 'libs,testing/logs,testing/6/sub-6'

  use-matrix:
    name: 'Snyk: ${{ matrix.job.relativePath }}'
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.job.cd }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: CMDs
        run: |
          ls -al
          pwd

      # - uses: snyk/actions/setup@master

      # - name: Snyk Test
      #   run: |
      #     snyk test
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
